// Mocks generated by Mockito 5.4.6 from annotations
// in batuga/test/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:batuga/core/domain/models/device.dart' as _i5;
import 'package:batuga/core/domain/models/messages.dart' as _i4;
import 'package:batuga/core/domain/models/user.dart' as _i7;
import 'package:batuga/core/domain/repositories/i_user_repository.dart' as _i6;
import 'package:batuga/core/domain/services/bluetooth_manager/i_bluetooth_manager.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IBluetoothManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBluetoothManager extends _i1.Mock implements _i2.IBluetoothManager {
  MockIBluetoothManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<String> get clientConnections =>
      (super.noSuchMethod(
            Invocation.getter(#clientConnections),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i3.Stream<_i4.Message> get incomingMessages =>
      (super.noSuchMethod(
            Invocation.getter(#incomingMessages),
            returnValue: _i3.Stream<_i4.Message>.empty(),
          )
          as _i3.Stream<_i4.Message>);

  @override
  _i3.Stream<List<_i5.Device>> get discoveredDevices =>
      (super.noSuchMethod(
            Invocation.getter(#discoveredDevices),
            returnValue: _i3.Stream<List<_i5.Device>>.empty(),
          )
          as _i3.Stream<List<_i5.Device>>);

  @override
  _i3.Future<void> startAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#startAdvertising, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> connectToDevice(_i5.Device? device) =>
      (super.noSuchMethod(
            Invocation.method(#connectToDevice, [device]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendMessage(_i4.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> startDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#startDiscovery, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refreshDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#refreshDiscovery, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i6.IUserRepository {
  MockIUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i7.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i7.User?>.value(),
          )
          as _i3.Future<_i7.User?>);

  @override
  _i3.Future<void> saveCurrentUser(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrentUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearCurrentUser, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isFirstLaunch() =>
      (super.noSuchMethod(
            Invocation.method(#isFirstLaunch, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setFirstLaunch(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setFirstLaunch, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
