name: batuga
description: "BaTuGa - игра по Bluetooth"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # BLoC для управления состоянием
  flutter_bloc: ^9.1.1
  bloc: ^9.0.1

  # Freezed для генерации кода
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Dependency Injection
  dep_gen: ^1.1.11

  # Bluetooth
  bluetooth_low_energy: ^6.1.0
  permission_handler: ^12.0.1

  # иконка приложения
  flutter_launcher_icons: ^0.14.4

  # нативный сплеш
  flutter_native_splash: ^2.4.6


  # Локализация
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Утилиты
  device_info_plus: ^12.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking library
  mockito: ^5.4.4
  bloc_test: ^10.0.0

  flutter_lints: ^6.0.0

  # Генераторы кода
  build_runner: ^2.4.10
  freezed: ^3.2.0
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#A0EBE1"
  color_dark: "#A0EBE1"
  image: "assets/images/splash_logo.png"
  image_dark: "assets/images/splash_logo.png"
  android_12:
    color: "#A0EBE1"
    color_dark: "#A0EBE1"
    image: "assets/images/splash_logo.png"
    image_dark: "assets/images/splash_logo.png"

