// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: type=lint
// coverage:ignore-start

import 'dart:collection';

import 'package:flutter/widgets.dart';

// **************************************************************************
// DepGen code generator
// This file was generated by running the command:
// flutter pub run dep_gen:generate -p lib/core/di
// **************************************************************************

import 'package:ble_peer_session/ble_peer_session.dart';
import 'package:flutter/material.dart';
import 'package:batuga/core/domain/repositories/device_repository.dart';
import 'package:batuga/core/domain/repositories/user_repository.dart';
import 'package:batuga/features/home/presentation/widgets/server_session_dialog/bloc/server_session_bloc.dart';
import 'package:batuga/features/home/presentation/widgets/nickname_dialog/bloc/nickname_bloc.dart';
import 'package:batuga/features/home/presentation/widgets/client_session_dialog/bloc/client_session_bloc.dart';
import 'package:batuga/features/home/presentation/bloc/home_bloc.dart';
import 'package:batuga/features/splash/presentation/bloc/splash_bloc.dart';
import 'package:batuga/features/games_list/presentation/bloc/games_list_bloc.dart';
import 'package:batuga/features/tictactoe/presentation/bloc/game_bloc.dart';

/// The environment in which all used dependency instances are configured
@immutable
class DepGenEnvironment {
  DepGenEnvironment({Map<Type, Object>? initialServices})
    : _environment = initialServices ?? {};

  late final Map<Type, Object> _environment;

  // ---------------------------------------------------------------------------
  /// An unsafe method for getting an instance by its type. You need to be sure
  /// that an instance of the requested type has been registered
  T g<T>() => _environment[T] as T;

  // ---------------------------------------------------------------------------
  /// A safe method for trying to get an instance by its type.
  T? mayBeGet<T>() => _environment.containsKey(T) ? _environment[T] as T : null;

  // ---------------------------------------------------------------------------
  /// Registration of an instance with an indication of its type. You cannot
  /// register multiple instances of the same type
  void registry<T>(Object instance) => _environment[T] = instance;

  // ---------------------------------------------------------------------------
  /// Is the collection of instances blocked
  bool get isLocked => _environment is UnmodifiableMapView;

  // ---------------------------------------------------------------------------
  /// Returns an instance of the environment settings with the collection
  /// blocked from changes
  DepGenEnvironment lock() {
    return DepGenEnvironment(initialServices: Map.unmodifiable(_environment));
  }
}

// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
extension DepProviderContextExtension on BuildContext {
  /// Obtain a value from the nearest ancestor DepProvider.
  DepProvider depGen() => DepProvider.of(this);
}

// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
class DepProvider extends InheritedWidget {
  const DepProvider({
    Key? key,
    required Widget child,
    required DepGenEnvironment environment,
  }) : _env = environment,
       super(key: key, child: child);

  // ---------------------------------------------------------------------------
  /// A pre-configured environment containing the dependencies used
  final DepGenEnvironment _env;
  DepGenEnvironment get environment => _env;

  // ---------------------------------------------------------------------------
  static DepProvider of(BuildContext context) {
    final DepProvider? dp = context
        .findAncestorWidgetOfExactType<DepProvider>();
    if (dp == null) {
      throw UnimplementedError('DepProvider is not initialized in context');
    }
    return dp;
  }

  // ---------------------------------------------------------------------------
  @override
  bool updateShouldNotify(DepProvider oldWidget) {
    return false;
  }

  // ---------------------------------------------------------------------------
  /// An unsafe method for getting an instance by its type. You need to be sure
  /// that an instance of the requested type has been registered
  T g<T>() => _env.g<T>();

  // ---------------------------------------------------------------------------
  /// A safe method for trying to get an instance by its type.
  T? mayBeGet<T>() => _env.mayBeGet<T>();

  // ---------------------------------------------------------------------------
  ServerSessionBloc buildServerSessionBloc() => ServerSessionBloc(
    userRepo: _env.g<UserRepository>(),
    deviceRepo: _env.g<DeviceRepository>(),
    session: _env.g<TransportSessionServer>(),
    transport: _env.g<TransportFacade>(),
  );

  // ---------------------------------------------------------------------------
  NicknameBloc buildNicknameBloc() =>
      NicknameBloc(userRepo: _env.g<UserRepository>());

  // ---------------------------------------------------------------------------
  ClientSessionBloc buildClientSessionBloc() => ClientSessionBloc(
    userRepo: _env.g<UserRepository>(),
    deviceRepo: _env.g<DeviceRepository>(),
    session: _env.g<TransportSessionClient>(),
    transport: _env.g<TransportFacade>(),
  );

  // ---------------------------------------------------------------------------
  HomeBloc buildHomeBloc() => HomeBloc(
    userRepo: _env.g<UserRepository>(),
    transport: _env.g<TransportFacade>(),
  );

  // ---------------------------------------------------------------------------
  SplashBloc buildSplashBloc() => SplashBloc(
    bluetoothPermissionsService: _env.g<BluetoothPermissionsService>(),
    bluetoothStateService: _env.g<BluetoothStateService>(),
  );

  // ---------------------------------------------------------------------------
  GamesListBloc buildGamesListBloc() => GamesListBloc();

  // ---------------------------------------------------------------------------
  GameBloc buildGameBloc() => GameBloc(
    transport: _env.g<TransportFacade>(),
    userRepository: _env.g<UserRepository>(),
  );
}

// coverage:ignore-end
